// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P229FirstApi.DAL;

#nullable disable

namespace P229FirstApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230405103209_AddedCategoriesTable")]
    partial class AddedCategoriesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("P229FirstApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1320),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1329),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1331),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1331),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1332),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 5, 14, 32, 9, 9, DateTimeKind.Utc).AddTicks(1333),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Samsung"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
