// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P229FirstApi.DAL;

#nullable disable

namespace P229FirstApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230405114012_AddedProductsTable")]
    partial class AddedProductsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("P229FirstApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("System");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6573),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6581),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6582),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6583),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6584),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6585),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("P229FirstApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6680),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6682),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6683),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6683),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6685),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6687),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6687),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6688),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6689),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6692),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6694),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6695),
                            CreatedBy = "System",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 4, 5, 15, 40, 12, 85, DateTimeKind.Utc).AddTicks(6696),
                            CreatedBy = "System",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("P229FirstApi.Entities.Product", b =>
                {
                    b.HasOne("P229FirstApi.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("P229FirstApi.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
